version: 2.1


jobs:
  build:
    docker:
      - image: hubmap/api-base-image:latest
    steps:
      - checkout

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:  cborromeo/circle_ci

